import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { User, Theme } from '../../types';
import GlassCard from '../ui/GlassCard';
import { ArrowRight, Check } from 'lucide-react';

interface OnboardingFlowProps {
  onComplete: (user: User) => void;
}

const OnboardingFlow: React.FC<OnboardingFlowProps> = ({ onComplete }) => {
  const [step, setStep] = useState(1);
  const [formData, setFormData] = useState<Partial<User>>({
    themePref: 'lover',
    quoteSource: 'pop',
    agentEnabled: true,
  });

  const handleNext = () => {
    if (step < 3) setStep(step + 1);
    else handleComplete();
  };

  const handleComplete = () => {
    if (formData.firstName && formData.major && formData.university) {
      const newUser: User = {
        id: 'user_1', // In a real app, generated by DB
        firstName: formData.firstName,
        major: formData.major,
        university: formData.university,
        themePref: formData.themePref || 'lover',
        quoteSource: formData.quoteSource || 'pop',
        agentEnabled: formData.agentEnabled || true,
      };
      onComplete(newUser);
    }
  };

  const themes: { id: Theme; name: string; color: string }[] = [
    { id: 'debut', name: 'Debut', color: 'bg-teal-400' },
    { id: 'fearless', name: 'Fearless', color: 'bg-yellow-400' },
    { id: 'speak_now', name: 'Speak Now', color: 'bg-purple-600' },
    { id: 'red', name: 'Red', color: 'bg-red-600' },
    { id: '1989', name: '1989', color: 'bg-sky-300' },
    { id: 'reputation', name: 'Reputation', color: 'bg-neutral-800' },
    { id: 'lover', name: 'Lover', color: 'bg-pink-300' },
    { id: 'folklore', name: 'Folklore', color: 'bg-gray-400' },
    { id: 'evermore', name: 'Evermore', color: 'bg-orange-800' },
    { id: 'midnights', name: 'Midnights', color: 'bg-indigo-900' },
    { id: 'ttpd', name: 'TTPD', color: 'bg-zinc-400' },
    { id: 'academic', name: 'Academic', color: 'bg-gray-200' },
  ];

  return (
    <div className="min-h-[100dvh] flex flex-col items-center justify-center p-4 relative overflow-hidden bg-background">
      {/* Background Decor */}
      <div className="absolute top-[-10%] right-[-5%] w-72 h-72 md:w-96 md:h-96 bg-primary opacity-20 blur-[80px] rounded-full" />
      <div className="absolute bottom-[-10%] left-[-5%] w-72 h-72 md:w-96 md:h-96 bg-accent opacity-20 blur-[80px] rounded-full" />

      <GlassCard className="w-full max-w-md relative z-10 flex flex-col justify-between shadow-2xl border-white/20">
        <div className="flex-1 py-4">
            <AnimatePresence mode="wait">
            {step === 1 && (
                <motion.div
                key="step1"
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                className="space-y-8 text-center"
                >
                <div className="space-y-2">
                    <h1 className="text-3xl md:text-4xl font-serif text-primary font-bold tracking-tight">Kryminologia UW</h1>
                    <p className="text-text-muted text-sm md:text-base">Skonfiguruj swoje centrum wiedzy.</p>
                </div>
                
                <div className="space-y-4">
                    <div className="space-y-4">
                        <input
                        type="text"
                        placeholder="Imię"
                        className="w-full bg-white/10 border border-white/20 rounded-2xl px-5 py-4 text-lg focus:outline-none focus:border-accent focus:bg-white/20 transition-all placeholder-text-muted/50 text-center"
                        value={formData.firstName || ''}
                        onChange={(e) => setFormData({ ...formData, firstName: e.target.value })}
                        />
                        <input
                        type="text"
                        placeholder="Uczelnia"
                        className="w-full bg-white/10 border border-white/20 rounded-2xl px-5 py-4 text-lg focus:outline-none focus:border-accent focus:bg-white/20 transition-all placeholder-text-muted/50 text-center"
                        value={formData.university || ''}
                        onChange={(e) => setFormData({ ...formData, university: e.target.value })}
                        />
                        <input
                        type="text"
                        placeholder="Kierunek"
                        className="w-full bg-white/10 border border-white/20 rounded-2xl px-5 py-4 text-lg focus:outline-none focus:border-accent focus:bg-white/20 transition-all placeholder-text-muted/50 text-center"
                        value={formData.major || ''}
                        onChange={(e) => setFormData({ ...formData, major: e.target.value })}
                        />
                    </div>
                </div>
                </motion.div>
            )}

            {step === 2 && (
                <motion.div
                key="step2"
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                className="space-y-6 text-center"
                >
                <div className="space-y-2">
                    <h2 className="text-3xl font-serif text-primary">Wybierz Styl</h2>
                    <p className="text-text-muted text-sm">Dopasuj wygląd aplikacji.</p>
                </div>
                
                <div className="grid grid-cols-2 gap-3 max-h-[50vh] overflow-y-auto custom-scrollbar p-1">
                    {themes.map((t) => (
                    <button
                        key={t.id}
                        onClick={() => setFormData({ ...formData, themePref: t.id })}
                        className={`p-4 rounded-2xl border transition-all flex flex-col items-center gap-3 ${
                        formData.themePref === t.id 
                            ? 'border-accent bg-accent/10 scale-[1.02] shadow-lg' 
                            : 'border-white/10 bg-white/5 hover:bg-white/10'
                        }`}
                    >
                        <div className={`w-8 h-8 rounded-full shadow-inner ${t.color}`} />
                        <span className="font-medium text-sm">{t.name}</span>
                    </button>
                    ))}
                </div>
                </motion.div>
            )}

            {step === 3 && (
                <motion.div
                key="step3"
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                className="space-y-8 text-center"
                >
                <h2 className="text-3xl font-serif text-primary">Personalizacja</h2>
                
                <div className="space-y-6">
                    <div className="space-y-3">
                        <label className="text-sm font-medium text-text-muted uppercase tracking-wider">Inspiracja (Cytaty)</label>
                        <div className="flex justify-center gap-2">
                        {['pop', 'stoic', 'legal'].map((opt) => (
                            <button
                            key={opt}
                            onClick={() => setFormData({ ...formData, quoteSource: opt as any })}
                            className={`px-6 py-3 rounded-xl capitalize text-sm font-medium transition-all ${
                                formData.quoteSource === opt 
                                ? 'bg-accent text-white shadow-lg shadow-accent/25' 
                                : 'bg-white/10 hover:bg-white/20'
                            }`}
                            >
                            {opt}
                            </button>
                        ))}
                        </div>
                    </div>

                    <button 
                    onClick={() => setFormData(p => ({...p, agentEnabled: !p.agentEnabled}))}
                    className={`w-full p-5 rounded-2xl border transition-all flex items-center gap-4 text-left group ${
                        formData.agentEnabled 
                        ? 'bg-accent/10 border-accent' 
                        : 'bg-white/5 border-white/10'
                    }`}
                    >
                    <div className={`w-8 h-8 rounded-full border flex items-center justify-center transition-colors ${
                        formData.agentEnabled ? 'bg-accent border-accent text-white' : 'border-white/30'
                    }`}>
                        {formData.agentEnabled && <Check size={16} />}
                    </div>
                    <div>
                        <h4 className={`font-semibold ${formData.agentEnabled ? 'text-primary' : 'text-text'}`}>AI Executive Planner</h4>
                        <p className="text-xs text-text-muted mt-0.5">Automatyczne planowanie nauki</p>
                    </div>
                    </button>
                </div>
                </motion.div>
            )}
            </AnimatePresence>
        </div>

        <div className="mt-8 pt-6 border-t border-white/10">
          <button
            onClick={handleNext}
            className="w-full flex items-center justify-center gap-2 bg-primary text-white p-4 rounded-2xl hover:opacity-90 transition-all font-semibold text-lg shadow-xl shadow-primary/20 active:scale-[0.98]"
          >
            {step === 3 ? 'Zakończ' : 'Dalej'} <ArrowRight size={20} />
          </button>
        </div>
      </GlassCard>
    </div>
  );
};

export default OnboardingFlow;