import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { User, Theme } from '../../types';
import GlassCard from '../ui/GlassCard';
import { ArrowRight, Check } from 'lucide-react';

interface OnboardingFlowProps {
  onComplete: (user: User) => void;
}

const OnboardingFlow: React.FC<OnboardingFlowProps> = ({ onComplete }) => {
  const [step, setStep] = useState(1);
  const [formData, setFormData] = useState<Partial<User>>({
    themePref: 'lover',
    quoteSource: 'pop',
    agentEnabled: true,
  });

  const handleNext = () => {
    if (step < 3) setStep(step + 1);
    else handleComplete();
  };

  const handleComplete = () => {
    if (formData.firstName && formData.major && formData.university) {
      const newUser: User = {
        id: 'user_1', // In a real app, generated by DB
        firstName: formData.firstName,
        major: formData.major,
        university: formData.university,
        themePref: formData.themePref || 'lover',
        quoteSource: formData.quoteSource || 'pop',
        agentEnabled: formData.agentEnabled || true,
      };
      onComplete(newUser);
    }
  };

  const themes: { id: Theme; name: string; color: string }[] = [
    { id: 'lover', name: 'Lover', color: 'bg-pink-200' },
    { id: 'reputation', name: 'Reputation', color: 'bg-neutral-900' },
    { id: 'midnights', name: 'Midnights', color: 'bg-indigo-900' },
    { id: 'academic', name: 'Academic', color: 'bg-gray-100' },
  ];

  return (
    <div className="min-h-screen flex items-center justify-center p-4 relative overflow-hidden">
      {/* Background Decor */}
      <div className="absolute top-[-10%] right-[-5%] w-96 h-96 bg-primary opacity-20 blur-3xl rounded-full" />
      <div className="absolute bottom-[-10%] left-[-5%] w-96 h-96 bg-accent opacity-20 blur-3xl rounded-full" />

      <GlassCard className="max-w-xl w-full relative z-10 min-h-[400px] flex flex-col justify-between">
        <AnimatePresence mode="wait">
          {step === 1 && (
            <motion.div
              key="step1"
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -20 }}
              className="space-y-6"
            >
              <h1 className="text-4xl font-serif text-primary font-bold">Welcome to Lover & Law</h1>
              <p className="text-text-muted">Let's set up your knowledge hub.</p>
              
              <div className="space-y-4">
                <input
                  type="text"
                  placeholder="First Name"
                  className="w-full bg-white/20 border border-white/30 rounded-lg px-4 py-3 focus:outline-none focus:ring-2 focus:ring-accent placeholder-text-muted/70"
                  value={formData.firstName || ''}
                  onChange={(e) => setFormData({ ...formData, firstName: e.target.value })}
                />
                 <input
                  type="text"
                  placeholder="University"
                  className="w-full bg-white/20 border border-white/30 rounded-lg px-4 py-3 focus:outline-none focus:ring-2 focus:ring-accent placeholder-text-muted/70"
                  value={formData.university || ''}
                  onChange={(e) => setFormData({ ...formData, university: e.target.value })}
                />
                <input
                  type="text"
                  placeholder="Major / Degree (e.g. Criminology)"
                  className="w-full bg-white/20 border border-white/30 rounded-lg px-4 py-3 focus:outline-none focus:ring-2 focus:ring-accent placeholder-text-muted/70"
                  value={formData.major || ''}
                  onChange={(e) => setFormData({ ...formData, major: e.target.value })}
                />
              </div>
            </motion.div>
          )}

          {step === 2 && (
            <motion.div
              key="step2"
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -20 }}
              className="space-y-6"
            >
              <h2 className="text-3xl font-serif text-primary">Choose your Era</h2>
              <p className="text-text-muted">Select a theme that matches your vibe.</p>
              
              <div className="grid grid-cols-2 gap-4">
                {themes.map((t) => (
                  <button
                    key={t.id}
                    onClick={() => setFormData({ ...formData, themePref: t.id })}
                    className={`p-4 rounded-xl border-2 transition-all flex items-center gap-3 ${
                      formData.themePref === t.id ? 'border-accent scale-105' : 'border-transparent hover:border-white/30'
                    } bg-white/10`}
                  >
                    <div className={`w-8 h-8 rounded-full ${t.color}`} />
                    <span className="font-medium">{t.name}</span>
                  </button>
                ))}
              </div>
            </motion.div>
          )}

          {step === 3 && (
            <motion.div
              key="step3"
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -20 }}
              className="space-y-6"
            >
              <h2 className="text-3xl font-serif text-primary">Final Touches</h2>
              
              <div className="space-y-4">
                <label className="block text-sm font-medium mb-2">Quote Inspiration Source</label>
                <div className="flex gap-2">
                  {['pop', 'stoic', 'legal'].map((opt) => (
                    <button
                      key={opt}
                      onClick={() => setFormData({ ...formData, quoteSource: opt as any })}
                      className={`px-4 py-2 rounded-lg capitalize ${
                        formData.quoteSource === opt ? 'bg-accent text-white' : 'bg-white/10'
                      }`}
                    >
                      {opt}
                    </button>
                  ))}
                </div>

                <div className="flex items-center gap-3 mt-8 p-4 bg-white/10 rounded-xl">
                  <div 
                    onClick={() => setFormData(p => ({...p, agentEnabled: !p.agentEnabled}))}
                    className={`w-6 h-6 rounded border cursor-pointer flex items-center justify-center ${formData.agentEnabled ? 'bg-accent border-accent' : 'border-white/40'}`}
                  >
                    {formData.agentEnabled && <Check size={14} className="text-white" />}
                  </div>
                  <div>
                    <h4 className="font-semibold">Enable The Executive Planner</h4>
                    <p className="text-xs text-text-muted">Allow Gemini AI to proactively schedule study blocks based on your workload.</p>
                  </div>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        <div className="flex justify-end mt-8">
          <button
            onClick={handleNext}
            className="flex items-center gap-2 bg-accent text-white px-6 py-3 rounded-full hover:bg-opacity-90 transition-all font-semibold shadow-lg shadow-accent/20"
          >
            {step === 3 ? 'Finish' : 'Next'} <ArrowRight size={18} />
          </button>
        </div>
      </GlassCard>
    </div>
  );
};

export default OnboardingFlow;
